services:
  - type: web
    name: nestjs-app
    runtime: node
    plan: free
    region: frankfurt # choose a region close to your users
    buildCommand: NPM_CONFIG_PRODUCTION=false npm ci && npm run build
    startCommand: npm run start:prod
    autoDeploy: true

    # If you have a health endpoint, set it here:
    # healthCheckPath: /health

    envVars:
      - key: DATABASE_URL
        sync: false # will be added in Render dashboard
      - key: COOKIE_KEY
        sync: false # will be added in Render dashboard
      # Optional: pin Node.js version used at runtime/build
      # - key: NODE_VERSION
      #   value: 20

    # Run DB migrations AFTER a successful deploy (tries both build layouts)
    postDeployCommand: >
      bash -lc '
      echo "=== DEBUG: list dist ===";
      ls -R dist || true;
      if [ -f dist/database/data-source.js ]; then
        echo "Running migrations with dist/database/data-source.js";
        npm run typeorm:prod -- migration:run -d dist/database/data-source.js;
      elif [ -f dist/src/database/data-source.js ]; then
        echo "Running migrations with dist/src/database/data-source.js";
        npm run typeorm:prod -- migration:run -d dist/src/database/data-source.js;
      else
        echo "ERROR: data-source.js not found in dist. Check tsconfig.build.json.";
        exit 1;
      fi'
