services:
  - type: web
    name: nestjs-app
    runtime: node
    plan: free
    region: frankfurt # choose a region close to your users
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    autoDeploy: true

    # If you have a health endpoint, set it here:
    # healthCheckPath: /health

    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # will be added in Render dashboard
      - key: COOKIE_KEY
        sync: false # will be added in Render dashboard

    # Run DB migrations AFTER a successful deploy:
    postDeployCommand: npm run migration:run
